service: aws-node-http-api-project
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:384074953804:table/TodoTable

functions:
  addTodo:
    handler: src/addTodo.handler
    events:
      - httpApi:
          path: /
          method: post
  fetchTodos:
    handler: src/fetchTodos.handler
    events:
      - httpApi:
          path: /
          method: get
  fetchTodo:
    handler: src/fetchTodo.handler
    events:
      - httpApi:
          path: /{id}
          method: get
  updateTodo:
      handler: src/updateTodo.handler
      events:
        - httpApi:
            path: /{id}
            method: put
  
